/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.smelldsl.ui.internal.SmelldslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SmellDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SmelldslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SmelldslActivator activator = SmelldslActivator.getInstance();
		return activator != null ? activator.getInjector(SmelldslActivator.ORG_SMELLDSL_SMELLDSL) : null;
	}

}
