/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.smelldsl.ui.internal.SmelldslActivator;

public class SmellDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SmelldslActivator.getInstance().getInjector("org.smelldsl.SmellDsl");
	}

}
