/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SmellDslUiModule extends AbstractSmellDslUiModule {

	public SmellDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
