/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl.smellDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.smelldsl.smellDsl.Feature;
import org.smelldsl.smellDsl.Measure;
import org.smelldsl.smellDsl.SmellDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Feature</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.smelldsl.smellDsl.impl.FeatureImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.smelldsl.smellDsl.impl.FeatureImpl#isOptscales <em>Optscales</em>}</li>
 *   <li>{@link org.smelldsl.smellDsl.impl.FeatureImpl#getMeasures <em>Measures</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FeatureImpl extends MinimalEObjectImpl.Container implements Feature
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #isOptscales() <em>Optscales</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOptscales()
   * @generated
   * @ordered
   */
  protected static final boolean OPTSCALES_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isOptscales() <em>Optscales</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOptscales()
   * @generated
   * @ordered
   */
  protected boolean optscales = OPTSCALES_EDEFAULT;

  /**
   * The cached value of the '{@link #getMeasures() <em>Measures</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMeasures()
   * @generated
   * @ordered
   */
  protected EList<Measure> measures;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FeatureImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmellDslPackage.Literals.FEATURE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmellDslPackage.FEATURE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isOptscales()
  {
    return optscales;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOptscales(boolean newOptscales)
  {
    boolean oldOptscales = optscales;
    optscales = newOptscales;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmellDslPackage.FEATURE__OPTSCALES, oldOptscales, optscales));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Measure> getMeasures()
  {
    if (measures == null)
    {
      measures = new EObjectContainmentEList<Measure>(Measure.class, this, SmellDslPackage.FEATURE__MEASURES);
    }
    return measures;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SmellDslPackage.FEATURE__MEASURES:
        return ((InternalEList<?>)getMeasures()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SmellDslPackage.FEATURE__NAME:
        return getName();
      case SmellDslPackage.FEATURE__OPTSCALES:
        return isOptscales();
      case SmellDslPackage.FEATURE__MEASURES:
        return getMeasures();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SmellDslPackage.FEATURE__NAME:
        setName((String)newValue);
        return;
      case SmellDslPackage.FEATURE__OPTSCALES:
        setOptscales((Boolean)newValue);
        return;
      case SmellDslPackage.FEATURE__MEASURES:
        getMeasures().clear();
        getMeasures().addAll((Collection<? extends Measure>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SmellDslPackage.FEATURE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case SmellDslPackage.FEATURE__OPTSCALES:
        setOptscales(OPTSCALES_EDEFAULT);
        return;
      case SmellDslPackage.FEATURE__MEASURES:
        getMeasures().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SmellDslPackage.FEATURE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case SmellDslPackage.FEATURE__OPTSCALES:
        return optscales != OPTSCALES_EDEFAULT;
      case SmellDslPackage.FEATURE__MEASURES:
        return measures != null && !measures.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", optscales: ");
    result.append(optscales);
    result.append(')');
    return result.toString();
  }

} //FeatureImpl
