/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl.smellDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.smelldsl.smellDsl.SmellDslPackage;
import org.smelldsl.smellDsl.SmellType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Smell Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SmellTypeImpl extends TypeImpl implements SmellType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SmellTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmellDslPackage.Literals.SMELL_TYPE;
  }

} //SmellTypeImpl
