/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SmellDslStandaloneSetup extends SmellDslStandaloneSetupGenerated {

	public static void doSetup() {
		new SmellDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
