/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.smelldsl.parser.antlr.internal.InternalSmellDslParser;
import org.smelldsl.services.SmellDslGrammarAccess;

public class SmellDslParser extends AbstractAntlrParser {

	@Inject
	private SmellDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSmellDslParser createParser(XtextTokenStream stream) {
		return new InternalSmellDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Domainmodel";
	}

	public SmellDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SmellDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
