/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSmellDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.smelldsl.smellDsl.SmellDslPackage.eINSTANCE);
		return result;
	}
}
