/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class SmellDslScopeProvider extends AbstractSmellDslScopeProvider {

}
