/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSmellDslScopeProvider extends DelegatingScopeProvider {
}
