/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl.smellDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logic Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.smelldsl.smellDsl.LogicExpression#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.smelldsl.smellDsl.LogicExpression#getLogicOperator <em>Logic Operator</em>}</li>
 *   <li>{@link org.smelldsl.smellDsl.LogicExpression#getLogicExpression <em>Logic Expression</em>}</li>
 * </ul>
 *
 * @see org.smelldsl.smellDsl.SmellDslPackage#getLogicExpression()
 * @model
 * @generated
 */
public interface LogicExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see org.smelldsl.smellDsl.SmellDslPackage#getLogicExpression_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link org.smelldsl.smellDsl.LogicExpression#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

  /**
   * Returns the value of the '<em><b>Logic Operator</b></em>' attribute.
   * The literals are from the enumeration {@link org.smelldsl.smellDsl.LogicOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logic Operator</em>' attribute.
   * @see org.smelldsl.smellDsl.LogicOperator
   * @see #setLogicOperator(LogicOperator)
   * @see org.smelldsl.smellDsl.SmellDslPackage#getLogicExpression_LogicOperator()
   * @model
   * @generated
   */
  LogicOperator getLogicOperator();

  /**
   * Sets the value of the '{@link org.smelldsl.smellDsl.LogicExpression#getLogicOperator <em>Logic Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logic Operator</em>' attribute.
   * @see org.smelldsl.smellDsl.LogicOperator
   * @see #getLogicOperator()
   * @generated
   */
  void setLogicOperator(LogicOperator value);

  /**
   * Returns the value of the '<em><b>Logic Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logic Expression</em>' containment reference.
   * @see #setLogicExpression(LogicExpression)
   * @see org.smelldsl.smellDsl.SmellDslPackage#getLogicExpression_LogicExpression()
   * @model containment="true"
   * @generated
   */
  LogicExpression getLogicExpression();

  /**
   * Sets the value of the '{@link org.smelldsl.smellDsl.LogicExpression#getLogicExpression <em>Logic Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logic Expression</em>' containment reference.
   * @see #getLogicExpression()
   * @generated
   */
  void setLogicExpression(LogicExpression value);

} // LogicExpression
