/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl.smellDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Optscale</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.smelldsl.smellDsl.Optscale#getScaletype <em>Scaletype</em>}</li>
 * </ul>
 *
 * @see org.smelldsl.smellDsl.SmellDslPackage#getOptscale()
 * @model
 * @generated
 */
public interface Optscale extends EObject
{
  /**
   * Returns the value of the '<em><b>Scaletype</b></em>' attribute.
   * The literals are from the enumeration {@link org.smelldsl.smellDsl.Scaletype}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scaletype</em>' attribute.
   * @see org.smelldsl.smellDsl.Scaletype
   * @see #setScaletype(Scaletype)
   * @see org.smelldsl.smellDsl.SmellDslPackage#getOptscale_Scaletype()
   * @model
   * @generated
   */
  Scaletype getScaletype();

  /**
   * Sets the value of the '{@link org.smelldsl.smellDsl.Optscale#getScaletype <em>Scaletype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scaletype</em>' attribute.
   * @see org.smelldsl.smellDsl.Scaletype
   * @see #getScaletype()
   * @generated
   */
  void setScaletype(Scaletype value);

} // Optscale
