/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl.smellDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.smelldsl.smellDsl.Rule#getLogicExpression <em>Logic Expression</em>}</li>
 *   <li>{@link org.smelldsl.smellDsl.Rule#getResult <em>Result</em>}</li>
 * </ul>
 *
 * @see org.smelldsl.smellDsl.SmellDslPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends Type
{
  /**
   * Returns the value of the '<em><b>Logic Expression</b></em>' containment reference list.
   * The list contents are of type {@link org.smelldsl.smellDsl.LogicExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logic Expression</em>' containment reference list.
   * @see org.smelldsl.smellDsl.SmellDslPackage#getRule_LogicExpression()
   * @model containment="true"
   * @generated
   */
  EList<LogicExpression> getLogicExpression();

  /**
   * Returns the value of the '<em><b>Result</b></em>' containment reference list.
   * The list contents are of type {@link org.smelldsl.smellDsl.Result}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Result</em>' containment reference list.
   * @see org.smelldsl.smellDsl.SmellDslPackage#getRule_Result()
   * @model containment="true"
   * @generated
   */
  EList<Result> getResult();

} // Rule
