/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl.smellDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Scaletype</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.smelldsl.smellDsl.SmellDslPackage#getScaletype()
 * @model
 * @generated
 */
public enum Scaletype implements Enumerator
{
  /**
   * The '<em><b>Nominal</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NOMINAL_VALUE
   * @generated
   * @ordered
   */
  NOMINAL(0, "Nominal", "Nominal"),

  /**
   * The '<em><b>Ordinal</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ORDINAL_VALUE
   * @generated
   * @ordered
   */
  ORDINAL(1, "Ordinal", "Ordinal"),

  /**
   * The '<em><b>Interval</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INTERVAL_VALUE
   * @generated
   * @ordered
   */
  INTERVAL(2, "Interval", "Interval"),

  /**
   * The '<em><b>Ratio</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RATIO_VALUE
   * @generated
   * @ordered
   */
  RATIO(3, "Ratio", "Ratio");

  /**
   * The '<em><b>Nominal</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NOMINAL
   * @model name="Nominal"
   * @generated
   * @ordered
   */
  public static final int NOMINAL_VALUE = 0;

  /**
   * The '<em><b>Ordinal</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ORDINAL
   * @model name="Ordinal"
   * @generated
   * @ordered
   */
  public static final int ORDINAL_VALUE = 1;

  /**
   * The '<em><b>Interval</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INTERVAL
   * @model name="Interval"
   * @generated
   * @ordered
   */
  public static final int INTERVAL_VALUE = 2;

  /**
   * The '<em><b>Ratio</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RATIO
   * @model name="Ratio"
   * @generated
   * @ordered
   */
  public static final int RATIO_VALUE = 3;

  /**
   * An array of all the '<em><b>Scaletype</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Scaletype[] VALUES_ARRAY =
    new Scaletype[]
    {
      NOMINAL,
      ORDINAL,
      INTERVAL,
      RATIO,
    };

  /**
   * A public read-only list of all the '<em><b>Scaletype</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Scaletype> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Scaletype</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Scaletype get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Scaletype result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Scaletype</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Scaletype getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Scaletype result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Scaletype</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Scaletype get(int value)
  {
    switch (value)
    {
      case NOMINAL_VALUE: return NOMINAL;
      case ORDINAL_VALUE: return ORDINAL;
      case INTERVAL_VALUE: return INTERVAL;
      case RATIO_VALUE: return RATIO;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Scaletype(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Scaletype
