/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl.smellDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Smell Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.smelldsl.smellDsl.SmellDslPackage#getSmellType()
 * @model
 * @generated
 */
public interface SmellType extends Type
{
} // SmellType
