/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl.smellDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Smell</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.smelldsl.smellDsl.Smell#getSuperType <em>Super Type</em>}</li>
 *   <li>{@link org.smelldsl.smellDsl.Smell#getSmellcontent <em>Smellcontent</em>}</li>
 *   <li>{@link org.smelldsl.smellDsl.Smell#isSymptom <em>Symptom</em>}</li>
 *   <li>{@link org.smelldsl.smellDsl.Smell#isTreatment <em>Treatment</em>}</li>
 * </ul>
 *
 * @see org.smelldsl.smellDsl.SmellDslPackage#getSmell()
 * @model
 * @generated
 */
public interface Smell extends Type
{
  /**
   * Returns the value of the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Type</em>' reference.
   * @see #setSuperType(SmellType)
   * @see org.smelldsl.smellDsl.SmellDslPackage#getSmell_SuperType()
   * @model
   * @generated
   */
  SmellType getSuperType();

  /**
   * Sets the value of the '{@link org.smelldsl.smellDsl.Smell#getSuperType <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Type</em>' reference.
   * @see #getSuperType()
   * @generated
   */
  void setSuperType(SmellType value);

  /**
   * Returns the value of the '<em><b>Smellcontent</b></em>' containment reference list.
   * The list contents are of type {@link org.smelldsl.smellDsl.Feature}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Smellcontent</em>' containment reference list.
   * @see org.smelldsl.smellDsl.SmellDslPackage#getSmell_Smellcontent()
   * @model containment="true"
   * @generated
   */
  EList<Feature> getSmellcontent();

  /**
   * Returns the value of the '<em><b>Symptom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Symptom</em>' attribute.
   * @see #setSymptom(boolean)
   * @see org.smelldsl.smellDsl.SmellDslPackage#getSmell_Symptom()
   * @model
   * @generated
   */
  boolean isSymptom();

  /**
   * Sets the value of the '{@link org.smelldsl.smellDsl.Smell#isSymptom <em>Symptom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Symptom</em>' attribute.
   * @see #isSymptom()
   * @generated
   */
  void setSymptom(boolean value);

  /**
   * Returns the value of the '<em><b>Treatment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Treatment</em>' attribute.
   * @see #setTreatment(boolean)
   * @see org.smelldsl.smellDsl.SmellDslPackage#getSmell_Treatment()
   * @model
   * @generated
   */
  boolean isTreatment();

  /**
   * Sets the value of the '{@link org.smelldsl.smellDsl.Smell#isTreatment <em>Treatment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Treatment</em>' attribute.
   * @see #isTreatment()
   * @generated
   */
  void setTreatment(boolean value);

} // Smell
