/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl.smellDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.smelldsl.smellDsl.SmellDslFactory
 * @model kind="package"
 * @generated
 */
public interface SmellDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "smellDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.smelldsl.org/SmellDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "smellDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SmellDslPackage eINSTANCE = org.smelldsl.smellDsl.impl.SmellDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.smelldsl.smellDsl.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.smelldsl.smellDsl.impl.DomainmodelImpl
   * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getDomainmodel()
   * @generated
   */
  int DOMAINMODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Domainmodel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.smelldsl.smellDsl.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.smelldsl.smellDsl.impl.TypeImpl
   * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getType()
   * @generated
   */
  int TYPE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.smelldsl.smellDsl.impl.SmellTypeImpl <em>Smell Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.smelldsl.smellDsl.impl.SmellTypeImpl
   * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getSmellType()
   * @generated
   */
  int SMELL_TYPE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMELL_TYPE__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Smell Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMELL_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.smelldsl.smellDsl.impl.SmellImpl <em>Smell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.smelldsl.smellDsl.impl.SmellImpl
   * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getSmell()
   * @generated
   */
  int SMELL = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMELL__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMELL__SUPER_TYPE = TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Smellcontent</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMELL__SMELLCONTENT = TYPE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Symptom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMELL__SYMPTOM = TYPE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Treatment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMELL__TREATMENT = TYPE_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Smell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMELL_FEATURE_COUNT = TYPE_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.smelldsl.smellDsl.impl.FeatureImpl <em>Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.smelldsl.smellDsl.impl.FeatureImpl
   * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getFeature()
   * @generated
   */
  int FEATURE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__NAME = 0;

  /**
   * The feature id for the '<em><b>Optscales</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__OPTSCALES = 1;

  /**
   * The feature id for the '<em><b>Measures</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__MEASURES = 2;

  /**
   * The number of structural features of the '<em>Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.smelldsl.smellDsl.impl.OptscaleImpl <em>Optscale</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.smelldsl.smellDsl.impl.OptscaleImpl
   * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getOptscale()
   * @generated
   */
  int OPTSCALE = 5;

  /**
   * The feature id for the '<em><b>Scaletype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTSCALE__SCALETYPE = 0;

  /**
   * The number of structural features of the '<em>Optscale</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTSCALE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.smelldsl.smellDsl.impl.MeasureImpl <em>Measure</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.smelldsl.smellDsl.impl.MeasureImpl
   * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getMeasure()
   * @generated
   */
  int MEASURE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEASURE__NAME = 0;

  /**
   * The feature id for the '<em><b>Measure</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEASURE__MEASURE = 1;

  /**
   * The number of structural features of the '<em>Measure</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEASURE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.smelldsl.smellDsl.impl.SymptomImpl <em>Symptom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.smelldsl.smellDsl.impl.SymptomImpl
   * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getSymptom()
   * @generated
   */
  int SYMPTOM = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYMPTOM__NAME = 0;

  /**
   * The number of structural features of the '<em>Symptom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYMPTOM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.smelldsl.smellDsl.impl.TreatmentImpl <em>Treatment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.smelldsl.smellDsl.impl.TreatmentImpl
   * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getTreatment()
   * @generated
   */
  int TREATMENT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREATMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Treatment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREATMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.smelldsl.smellDsl.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.smelldsl.smellDsl.impl.RuleImpl
   * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getRule()
   * @generated
   */
  int RULE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Logic Expression</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__LOGIC_EXPRESSION = TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Result</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__RESULT = TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.smelldsl.smellDsl.impl.LogicExpressionImpl <em>Logic Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.smelldsl.smellDsl.impl.LogicExpressionImpl
   * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getLogicExpression()
   * @generated
   */
  int LOGIC_EXPRESSION = 10;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXPRESSION__EXPRESSION = 0;

  /**
   * The feature id for the '<em><b>Logic Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXPRESSION__LOGIC_OPERATOR = 1;

  /**
   * The feature id for the '<em><b>Logic Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXPRESSION__LOGIC_EXPRESSION = 2;

  /**
   * The number of structural features of the '<em>Logic Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXPRESSION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.smelldsl.smellDsl.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.smelldsl.smellDsl.impl.ExpressionImpl
   * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 11;

  /**
   * The feature id for the '<em><b>Relational Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__RELATIONAL_OPERATOR = 0;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.smelldsl.smellDsl.impl.ResultImpl <em>Result</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.smelldsl.smellDsl.impl.ResultImpl
   * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getResult()
   * @generated
   */
  int RESULT = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESULT__NAME = 0;

  /**
   * The number of structural features of the '<em>Result</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESULT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.smelldsl.smellDsl.Scaletype <em>Scaletype</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.smelldsl.smellDsl.Scaletype
   * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getScaletype()
   * @generated
   */
  int SCALETYPE = 13;

  /**
   * The meta object id for the '{@link org.smelldsl.smellDsl.LogicOperator <em>Logic Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.smelldsl.smellDsl.LogicOperator
   * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getLogicOperator()
   * @generated
   */
  int LOGIC_OPERATOR = 14;

  /**
   * The meta object id for the '{@link org.smelldsl.smellDsl.RelationalOperator <em>Relational Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.smelldsl.smellDsl.RelationalOperator
   * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getRelationalOperator()
   * @generated
   */
  int RELATIONAL_OPERATOR = 15;


  /**
   * Returns the meta object for class '{@link org.smelldsl.smellDsl.Domainmodel <em>Domainmodel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domainmodel</em>'.
   * @see org.smelldsl.smellDsl.Domainmodel
   * @generated
   */
  EClass getDomainmodel();

  /**
   * Returns the meta object for the containment reference list '{@link org.smelldsl.smellDsl.Domainmodel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.smelldsl.smellDsl.Domainmodel#getElements()
   * @see #getDomainmodel()
   * @generated
   */
  EReference getDomainmodel_Elements();

  /**
   * Returns the meta object for class '{@link org.smelldsl.smellDsl.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.smelldsl.smellDsl.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link org.smelldsl.smellDsl.Type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.smelldsl.smellDsl.Type#getName()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Name();

  /**
   * Returns the meta object for class '{@link org.smelldsl.smellDsl.SmellType <em>Smell Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Smell Type</em>'.
   * @see org.smelldsl.smellDsl.SmellType
   * @generated
   */
  EClass getSmellType();

  /**
   * Returns the meta object for class '{@link org.smelldsl.smellDsl.Smell <em>Smell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Smell</em>'.
   * @see org.smelldsl.smellDsl.Smell
   * @generated
   */
  EClass getSmell();

  /**
   * Returns the meta object for the reference '{@link org.smelldsl.smellDsl.Smell#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see org.smelldsl.smellDsl.Smell#getSuperType()
   * @see #getSmell()
   * @generated
   */
  EReference getSmell_SuperType();

  /**
   * Returns the meta object for the containment reference list '{@link org.smelldsl.smellDsl.Smell#getSmellcontent <em>Smellcontent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Smellcontent</em>'.
   * @see org.smelldsl.smellDsl.Smell#getSmellcontent()
   * @see #getSmell()
   * @generated
   */
  EReference getSmell_Smellcontent();

  /**
   * Returns the meta object for the attribute '{@link org.smelldsl.smellDsl.Smell#isSymptom <em>Symptom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Symptom</em>'.
   * @see org.smelldsl.smellDsl.Smell#isSymptom()
   * @see #getSmell()
   * @generated
   */
  EAttribute getSmell_Symptom();

  /**
   * Returns the meta object for the attribute '{@link org.smelldsl.smellDsl.Smell#isTreatment <em>Treatment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Treatment</em>'.
   * @see org.smelldsl.smellDsl.Smell#isTreatment()
   * @see #getSmell()
   * @generated
   */
  EAttribute getSmell_Treatment();

  /**
   * Returns the meta object for class '{@link org.smelldsl.smellDsl.Feature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature</em>'.
   * @see org.smelldsl.smellDsl.Feature
   * @generated
   */
  EClass getFeature();

  /**
   * Returns the meta object for the attribute '{@link org.smelldsl.smellDsl.Feature#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.smelldsl.smellDsl.Feature#getName()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_Name();

  /**
   * Returns the meta object for the attribute '{@link org.smelldsl.smellDsl.Feature#isOptscales <em>Optscales</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Optscales</em>'.
   * @see org.smelldsl.smellDsl.Feature#isOptscales()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_Optscales();

  /**
   * Returns the meta object for the containment reference list '{@link org.smelldsl.smellDsl.Feature#getMeasures <em>Measures</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Measures</em>'.
   * @see org.smelldsl.smellDsl.Feature#getMeasures()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_Measures();

  /**
   * Returns the meta object for class '{@link org.smelldsl.smellDsl.Optscale <em>Optscale</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Optscale</em>'.
   * @see org.smelldsl.smellDsl.Optscale
   * @generated
   */
  EClass getOptscale();

  /**
   * Returns the meta object for the attribute '{@link org.smelldsl.smellDsl.Optscale#getScaletype <em>Scaletype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Scaletype</em>'.
   * @see org.smelldsl.smellDsl.Optscale#getScaletype()
   * @see #getOptscale()
   * @generated
   */
  EAttribute getOptscale_Scaletype();

  /**
   * Returns the meta object for class '{@link org.smelldsl.smellDsl.Measure <em>Measure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Measure</em>'.
   * @see org.smelldsl.smellDsl.Measure
   * @generated
   */
  EClass getMeasure();

  /**
   * Returns the meta object for the attribute '{@link org.smelldsl.smellDsl.Measure#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.smelldsl.smellDsl.Measure#getName()
   * @see #getMeasure()
   * @generated
   */
  EAttribute getMeasure_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.smelldsl.smellDsl.Measure#getMeasure <em>Measure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Measure</em>'.
   * @see org.smelldsl.smellDsl.Measure#getMeasure()
   * @see #getMeasure()
   * @generated
   */
  EReference getMeasure_Measure();

  /**
   * Returns the meta object for class '{@link org.smelldsl.smellDsl.Symptom <em>Symptom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Symptom</em>'.
   * @see org.smelldsl.smellDsl.Symptom
   * @generated
   */
  EClass getSymptom();

  /**
   * Returns the meta object for the attribute '{@link org.smelldsl.smellDsl.Symptom#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.smelldsl.smellDsl.Symptom#getName()
   * @see #getSymptom()
   * @generated
   */
  EAttribute getSymptom_Name();

  /**
   * Returns the meta object for class '{@link org.smelldsl.smellDsl.Treatment <em>Treatment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Treatment</em>'.
   * @see org.smelldsl.smellDsl.Treatment
   * @generated
   */
  EClass getTreatment();

  /**
   * Returns the meta object for the attribute '{@link org.smelldsl.smellDsl.Treatment#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.smelldsl.smellDsl.Treatment#getName()
   * @see #getTreatment()
   * @generated
   */
  EAttribute getTreatment_Name();

  /**
   * Returns the meta object for class '{@link org.smelldsl.smellDsl.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see org.smelldsl.smellDsl.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the containment reference list '{@link org.smelldsl.smellDsl.Rule#getLogicExpression <em>Logic Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Logic Expression</em>'.
   * @see org.smelldsl.smellDsl.Rule#getLogicExpression()
   * @see #getRule()
   * @generated
   */
  EReference getRule_LogicExpression();

  /**
   * Returns the meta object for the containment reference list '{@link org.smelldsl.smellDsl.Rule#getResult <em>Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Result</em>'.
   * @see org.smelldsl.smellDsl.Rule#getResult()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Result();

  /**
   * Returns the meta object for class '{@link org.smelldsl.smellDsl.LogicExpression <em>Logic Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logic Expression</em>'.
   * @see org.smelldsl.smellDsl.LogicExpression
   * @generated
   */
  EClass getLogicExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.smelldsl.smellDsl.LogicExpression#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see org.smelldsl.smellDsl.LogicExpression#getExpression()
   * @see #getLogicExpression()
   * @generated
   */
  EReference getLogicExpression_Expression();

  /**
   * Returns the meta object for the attribute '{@link org.smelldsl.smellDsl.LogicExpression#getLogicOperator <em>Logic Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Logic Operator</em>'.
   * @see org.smelldsl.smellDsl.LogicExpression#getLogicOperator()
   * @see #getLogicExpression()
   * @generated
   */
  EAttribute getLogicExpression_LogicOperator();

  /**
   * Returns the meta object for the containment reference '{@link org.smelldsl.smellDsl.LogicExpression#getLogicExpression <em>Logic Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Logic Expression</em>'.
   * @see org.smelldsl.smellDsl.LogicExpression#getLogicExpression()
   * @see #getLogicExpression()
   * @generated
   */
  EReference getLogicExpression_LogicExpression();

  /**
   * Returns the meta object for class '{@link org.smelldsl.smellDsl.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.smelldsl.smellDsl.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the attribute list '{@link org.smelldsl.smellDsl.Expression#getRelationalOperator <em>Relational Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Relational Operator</em>'.
   * @see org.smelldsl.smellDsl.Expression#getRelationalOperator()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_RelationalOperator();

  /**
   * Returns the meta object for class '{@link org.smelldsl.smellDsl.Result <em>Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Result</em>'.
   * @see org.smelldsl.smellDsl.Result
   * @generated
   */
  EClass getResult();

  /**
   * Returns the meta object for the attribute '{@link org.smelldsl.smellDsl.Result#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.smelldsl.smellDsl.Result#getName()
   * @see #getResult()
   * @generated
   */
  EAttribute getResult_Name();

  /**
   * Returns the meta object for enum '{@link org.smelldsl.smellDsl.Scaletype <em>Scaletype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Scaletype</em>'.
   * @see org.smelldsl.smellDsl.Scaletype
   * @generated
   */
  EEnum getScaletype();

  /**
   * Returns the meta object for enum '{@link org.smelldsl.smellDsl.LogicOperator <em>Logic Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Logic Operator</em>'.
   * @see org.smelldsl.smellDsl.LogicOperator
   * @generated
   */
  EEnum getLogicOperator();

  /**
   * Returns the meta object for enum '{@link org.smelldsl.smellDsl.RelationalOperator <em>Relational Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Relational Operator</em>'.
   * @see org.smelldsl.smellDsl.RelationalOperator
   * @generated
   */
  EEnum getRelationalOperator();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SmellDslFactory getSmellDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.smelldsl.smellDsl.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.smelldsl.smellDsl.impl.DomainmodelImpl
     * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getDomainmodel()
     * @generated
     */
    EClass DOMAINMODEL = eINSTANCE.getDomainmodel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAINMODEL__ELEMENTS = eINSTANCE.getDomainmodel_Elements();

    /**
     * The meta object literal for the '{@link org.smelldsl.smellDsl.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.smelldsl.smellDsl.impl.TypeImpl
     * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
     * The meta object literal for the '{@link org.smelldsl.smellDsl.impl.SmellTypeImpl <em>Smell Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.smelldsl.smellDsl.impl.SmellTypeImpl
     * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getSmellType()
     * @generated
     */
    EClass SMELL_TYPE = eINSTANCE.getSmellType();

    /**
     * The meta object literal for the '{@link org.smelldsl.smellDsl.impl.SmellImpl <em>Smell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.smelldsl.smellDsl.impl.SmellImpl
     * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getSmell()
     * @generated
     */
    EClass SMELL = eINSTANCE.getSmell();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SMELL__SUPER_TYPE = eINSTANCE.getSmell_SuperType();

    /**
     * The meta object literal for the '<em><b>Smellcontent</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SMELL__SMELLCONTENT = eINSTANCE.getSmell_Smellcontent();

    /**
     * The meta object literal for the '<em><b>Symptom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SMELL__SYMPTOM = eINSTANCE.getSmell_Symptom();

    /**
     * The meta object literal for the '<em><b>Treatment</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SMELL__TREATMENT = eINSTANCE.getSmell_Treatment();

    /**
     * The meta object literal for the '{@link org.smelldsl.smellDsl.impl.FeatureImpl <em>Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.smelldsl.smellDsl.impl.FeatureImpl
     * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getFeature()
     * @generated
     */
    EClass FEATURE = eINSTANCE.getFeature();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__NAME = eINSTANCE.getFeature_Name();

    /**
     * The meta object literal for the '<em><b>Optscales</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__OPTSCALES = eINSTANCE.getFeature_Optscales();

    /**
     * The meta object literal for the '<em><b>Measures</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__MEASURES = eINSTANCE.getFeature_Measures();

    /**
     * The meta object literal for the '{@link org.smelldsl.smellDsl.impl.OptscaleImpl <em>Optscale</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.smelldsl.smellDsl.impl.OptscaleImpl
     * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getOptscale()
     * @generated
     */
    EClass OPTSCALE = eINSTANCE.getOptscale();

    /**
     * The meta object literal for the '<em><b>Scaletype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTSCALE__SCALETYPE = eINSTANCE.getOptscale_Scaletype();

    /**
     * The meta object literal for the '{@link org.smelldsl.smellDsl.impl.MeasureImpl <em>Measure</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.smelldsl.smellDsl.impl.MeasureImpl
     * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getMeasure()
     * @generated
     */
    EClass MEASURE = eINSTANCE.getMeasure();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEASURE__NAME = eINSTANCE.getMeasure_Name();

    /**
     * The meta object literal for the '<em><b>Measure</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MEASURE__MEASURE = eINSTANCE.getMeasure_Measure();

    /**
     * The meta object literal for the '{@link org.smelldsl.smellDsl.impl.SymptomImpl <em>Symptom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.smelldsl.smellDsl.impl.SymptomImpl
     * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getSymptom()
     * @generated
     */
    EClass SYMPTOM = eINSTANCE.getSymptom();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYMPTOM__NAME = eINSTANCE.getSymptom_Name();

    /**
     * The meta object literal for the '{@link org.smelldsl.smellDsl.impl.TreatmentImpl <em>Treatment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.smelldsl.smellDsl.impl.TreatmentImpl
     * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getTreatment()
     * @generated
     */
    EClass TREATMENT = eINSTANCE.getTreatment();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TREATMENT__NAME = eINSTANCE.getTreatment_Name();

    /**
     * The meta object literal for the '{@link org.smelldsl.smellDsl.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.smelldsl.smellDsl.impl.RuleImpl
     * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Logic Expression</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__LOGIC_EXPRESSION = eINSTANCE.getRule_LogicExpression();

    /**
     * The meta object literal for the '<em><b>Result</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__RESULT = eINSTANCE.getRule_Result();

    /**
     * The meta object literal for the '{@link org.smelldsl.smellDsl.impl.LogicExpressionImpl <em>Logic Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.smelldsl.smellDsl.impl.LogicExpressionImpl
     * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getLogicExpression()
     * @generated
     */
    EClass LOGIC_EXPRESSION = eINSTANCE.getLogicExpression();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOGIC_EXPRESSION__EXPRESSION = eINSTANCE.getLogicExpression_Expression();

    /**
     * The meta object literal for the '<em><b>Logic Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOGIC_EXPRESSION__LOGIC_OPERATOR = eINSTANCE.getLogicExpression_LogicOperator();

    /**
     * The meta object literal for the '<em><b>Logic Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOGIC_EXPRESSION__LOGIC_EXPRESSION = eINSTANCE.getLogicExpression_LogicExpression();

    /**
     * The meta object literal for the '{@link org.smelldsl.smellDsl.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.smelldsl.smellDsl.impl.ExpressionImpl
     * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Relational Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__RELATIONAL_OPERATOR = eINSTANCE.getExpression_RelationalOperator();

    /**
     * The meta object literal for the '{@link org.smelldsl.smellDsl.impl.ResultImpl <em>Result</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.smelldsl.smellDsl.impl.ResultImpl
     * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getResult()
     * @generated
     */
    EClass RESULT = eINSTANCE.getResult();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESULT__NAME = eINSTANCE.getResult_Name();

    /**
     * The meta object literal for the '{@link org.smelldsl.smellDsl.Scaletype <em>Scaletype</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.smelldsl.smellDsl.Scaletype
     * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getScaletype()
     * @generated
     */
    EEnum SCALETYPE = eINSTANCE.getScaletype();

    /**
     * The meta object literal for the '{@link org.smelldsl.smellDsl.LogicOperator <em>Logic Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.smelldsl.smellDsl.LogicOperator
     * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getLogicOperator()
     * @generated
     */
    EEnum LOGIC_OPERATOR = eINSTANCE.getLogicOperator();

    /**
     * The meta object literal for the '{@link org.smelldsl.smellDsl.RelationalOperator <em>Relational Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.smelldsl.smellDsl.RelationalOperator
     * @see org.smelldsl.smellDsl.impl.SmellDslPackageImpl#getRelationalOperator()
     * @generated
     */
    EEnum RELATIONAL_OPERATOR = eINSTANCE.getRelationalOperator();

  }

} //SmellDslPackage
