/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.smelldsl.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class SmellDslProposalProvider extends AbstractSmellDslProposalProvider {
}
